services:
    sonata.admin.airports:
        class: Acme\AdminBundle\Admin\AirportsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Список стран" }
        arguments:
            - ~
            - Acme\AdminBundle\Entity\AviaAirports
            - SonataAdminBundle:CRUD
        calls:
            - [ setTranslationDomain, [AcmeAdminBundle]]