services:
    sonata.admin.airports:
        class: Acme\AdminBundle\Admin\AirportsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Список аэропортов" }
        arguments:
            - ~
            - Acme\AdminBundle\Entity\AviaAirports
            - ~
        calls:
            - [ setTranslationDomain, [AcmeAdminBundle]]
    sonata.admin.country:
        class: Acme\AdminBundle\Admin\CountryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Список стран" }
        arguments:
            - ~
            - Acme\AdminBundle\Entity\Country
            - ~
        calls:
            - [ setTranslationDomain, [AcmeAdminBundle]]

    sonata.admin.seo:
        class: Acme\AdminBundle\Admin\SeoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Контент", label: "Список СЕО" }
        arguments:
            - ~
            - Acme\AdminBundle\Entity\Seo
            - ~
        calls:
            - [ setTranslationDomain, [AcmeAdminBundle]]
    sonata.admin.order:
        class: Acme\AdminBundle\Admin\OrderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Заказы", label: "Список заказов" }
        arguments:
            - ~
            - Acme\AdminBundle\Entity\Order
            - ~
        calls:
            - [ setTranslationDomain, [AcmeAdminBundle]]