
assetic:
    assets:
        bootstrap_css:
            inputs:
                - bundles/acmeadmin/lib/bootstrap/less/bootstrap.less
            output: assets/css/bootstrap.css
        bootstrap_js:
            inputs:
                - bundles/acmeadmin/lib/bootstrap/js/tooltip.js
                - bundles/acmeadmin/lib/bootstrap/js/dropdown.js
                - bundles/acmeadmin/lib/bootstrap/js/affix.js
                - bundles/acmeadmin/lib/bootstrap/js/alert.js
                - bundles/acmeadmin/lib/bootstrap/js/button.js
                - bundles/acmeadmin/lib/bootstrap/js/carousel.js
                - bundles/acmeadmin/lib/bootstrap/js/collapse.js
                - bundles/acmeadmin/lib/bootstrap/js/modal.js
                - bundles/acmeadmin/lib/bootstrap/js/popover.js
                - bundles/acmeadmin/lib/bootstrap/js/scrollspy.js
                - bundles/acmeadmin/lib/bootstrap/js/tab.js
                - bundles/acmeadmin/lib/bootstrap/js/transition.js
            output: js/defaultbootstrap.js
        admin_common_js:
            inputs :
                - @AcmeAdminBundle/Resources/public/js/common.js
            output: js/assets/admin_common.js