admin_homepage:
  pattern: /
  defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: admin.page.index
      permanent: true


admin_view:
    pattern: /bootstrap
    defaults: { _controller: AcmeAdminBundle:Bootstrap:index }



bootstrap_edit:
    pattern:  /bootstrap/edit/{id}
    defaults: { _controller: AcmeBootstrapBundle:Default:index }
bootstrap_delete:
    pattern:  /bootstrap/delete/{id}
    defaults: { _controller: AcmeAdminBundle:Bootstrap:delete }
