admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

#admin_homepage:
#  pattern: /
#  defaults:
#      _controller: FrameworkBundle:Redirect:redirect
#      route: admin.order.index
#      permanent: true
#
#
#admin_view:
#    pattern: /bootstrap
#    defaults: { _controller: AcmeAdminBundle:Bootstrap:index }
#
#
#
#bootstrap_edit:
#    pattern:  /bootstrap/edit/{id}
#    defaults: { _controller: AcmeBootstrapBundle:Default:index }
#bootstrap_delete:
#    pattern:  /bootstrap/delete/{id}
#    defaults: { _controller: AcmeAdminBundle:Bootstrap:delete }
