parameters:



services:
#    admin.project.model:
#          class: Acme\AdminBundle\
    admin.routing_loader:
          class: Acme\AdminBundle\Routing\ControllerLoader
          arguments:
              - @kernel
          tags:
              - { name: routing.loader }
    admin.order.manager :
          class: Acme\AdminBundle\Model\Order
          arguments:
              - "@service_container"
              - Acme\AdminBundle\Entity\Order

