parameters:



services:
#    admin.project.model:
#          class: Acme\AdminBundle\
    admin.routing_loader:
          class: Acme\AdminBundle\Routing\ControllerLoader
          arguments:
              - @kernel
          tags:
              - { name: routing.loader }
    admin.order.manager :
          class: Acme\AdminBundle\Model\Order
          arguments:
              - "@service_container"
              - Acme\AdminBundle\Entity\Order
    admin.city.manager :
          class: Acme\AdminBundle\Model\City
          arguments:
              - "@service_container"
              - Acme\AdminBundle\Entity\City

    main.log.manager :
              class: Acme\AdminBundle\Model\Log
              arguments:
                  - "@service_container"
                  - Acme\AdminBundle\Entity\Log

