imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assets.yml }


framework:
    #esi:             ~
    translator:      { fallback: ru }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 8
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
              - 'AcmeCoreBundle:Form:form_layout.html.twig'
              - 'AcmeCoreBundle:Form:multifield.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['AcmeAdminBundle','AcmeMediaBundle','AcmeUserBundle', 'AcmeCoreBundle', 'BundlesDefaultBundle','StbBootstrapBundle','FOSUserBundle']
    #java: /usr/bin/java
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to:   "\.less$"
        cssrewrite: ~
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
#            apply_to:   "\.css$"
#        yui_js:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
#            apply_to:   "\.js$"
#    assets:

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
    
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Acme\UserBundle\Entity\User



bundles_default:
    count_on_page: 20

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default


#lsw_memcache:
#    session:
#        client: default
#    clients:
#        default:
#            hosts:
#              - { dsn: localhost, port: 11211 }

parameters:
    api_caller.options:
        timeout: 600  # maximum transport + execution duration of the call in sec.
#        ssl_verifypeer: false  # to stop cURL from verifying the peer's certificate.
#        useragent: "LeaseWeb API Caller"  # contents of the "User-Agent: " header.
#        followlocation: true  # to follow any "Location: " header that the server sends.
#        sslversion: 3  # set to 3 to avoid any bugs that relate to automatic version selection.
#        fresh_connect: false  # set to true to force full reconnect every call.

fos_js_routing:
    routes_to_expose: [ bundles_default_api_list,bundles_default_api_flights_items,bundles_default_api_calendar,bundles_default_change_locale,bundles_default_search_city ]

