bundles_yandex_avia:
    resource: "@BundlesYandexAviaBundle/Resources/config/routing.yml"
    prefix:   /api/yandex/avia



bundles_default:
    resource: "@BundlesDefaultBundle/Resources/config/routing.yml"
    prefix:   /

acme_core:
    resource: "@AcmeCoreBundle/Resources/config/routing.yml"
    prefix:   /admin

acme_admin:
    resource: "@AcmeAdminBundle/Resources/config/routing.yml"
    prefix:   /admin
acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

#AcmeAdminBundle_Extra:
#    resource: .
#    type: extra
#    prefix:   /admin
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

bundles_defaul.page_generator:
    path: /{uri}
    defaults:
      _controller: BundlesDefaultBundle:PageGenerator:index
    requirements:
        uri: ".+\/{1}$"
    methods: [GET]
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
#
#_imagine:
#    resource: .
#    type:     imagine
    
    

    
  

