ALTER TABLE menu ADD `uri` VARCHAR(255) DEFAULT NULL

CREATE TABLE news_partition (`id` INT AUTO_INCREMENT NOT NULL, `name` VARCHAR(100) NOT NULL, `show` TINYINT(1) NOT NULL, `uri` VARCHAR(255) NOT NULL, PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE news (partition_id INT DEFAULT NULL, `id` INT AUTO_INCREMENT NOT NULL, `name` VARCHAR(100) NOT NULL, `show` TINYINT(1) NOT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` LONGTEXT DEFAULT NULL, `text` LONGTEXT DEFAULT NULL, INDEX IDX_1DD3995030D5A4AB (partition_id), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE news ADD CONSTRAINT FK_1DD3995030D5A4AB FOREIGN KEY (partition_id) REFERENCES news_partition (id)

