bundles_default_rest_api_ticket:
    type:     rest
    resource: @BundlesDefaultBundle/Controller/Api/TicketController.php
    name_prefix: api_

bundles_default_rest_api_airport:
    type:     rest
    resource: @BundlesDefaultBundle/Controller/Api/AirportController.php
    name_prefix: api_

bundles_default_rest_api_book:
    type:     rest
    resource: @BundlesDefaultBundle/Controller/Api/BookController.php
    name_prefix: api_book_