assetic:
    assets :
        front_bootstrap_css:
                    inputs:
                        - bundles/bundlesdefault/lib/bootstrap/less/bootstrap.less
                    output: assets/css/b.css
        front_bootstrap_js:
            inputs:
                - bundles/bundlesdefault/lib/bootstrap/js/tooltip.js
                - bundles/bundlesdefault/lib/bootstrap/js/dropdown.js
                - bundles/bundlesdefault/lib/bootstrap/js/affix.js
                - bundles/bundlesdefault/lib/bootstrap/js/alert.js
                - bundles/bundlesdefault/lib/bootstrap/js/button.js
                - bundles/bundlesdefault/lib/bootstrap/js/carousel.js
                - bundles/bundlesdefault/lib/bootstrap/js/collapse.js
                - bundles/bundlesdefault/lib/bootstrap/js/modal.js
                - bundles/bundlesdefault/lib/bootstrap/js/popover.js
                - bundles/bundlesdefault/lib/bootstrap/js/scrollspy.js
                - bundles/bundlesdefault/lib/bootstrap/js/tab.js
                - bundles/bundlesdefault/lib/bootstrap/js/transition.js
            output: assets/js/b.js