Api:
    type: rest
    prefix: /api
    resource: "@BundlesDefaultBundle/Resources/config/api_routing.yml"
SPA:
  resource: "@BundlesDefaultBundle/Resources/config/spa_routing.yml"
bundles_default_homepage:
    pattern:  /
    defaults: { _controller: BundlesDefaultBundle:Default:index }

bundles_default.currency.change_currency:
    pattern: /currency/change-currency/{currency}
    defaults: { _controller: BundlesDefaultBundle:Currency:index}

bundles_default_search:
    pattern:  /api/search
    defaults: { _controller: BundlesDefaultBundle:Api:search }
bundles_default.order.search:
    pattern: payonline
    defaults: {_controller: BundlesDefaultBundle:Order:searchPnr}


bundles_default_search_complex_search:
    pattern:  /complex-search/{city}/{date}/{adults}/{return_way}/{children}/{infant}/{class}/{avia_company}/{direct_flights}
    defaults: { _controller: BundlesDefaultBundle:Search:complexSearch,adults: 1,class: Y ,children: 0,infant: 0,return_way : 2,direct_flights: 0, avia_company: all}
    requirements:
          city: "[\w\-]+"
          date: "[\d\-_]+"
          direct_flights:  0|1
          return_way:  0|1|2
          adults: \d

bundles_default_search_complex_search_items:
    pattern:  /complex-search/items/{city}/{date}/{adults}/{returnWay}/{children}/{infant}/{class}/{airline}/{directFlights}
    defaults: { _controller: BundlesDefaultBundle:Search:getComplexFilteredItems,adults: 1,class: Y ,children: 0,infant: 0,returnWay : 2,directFlights: 0,airline: all}
    requirements:
          city: "[\w\-]+"
          date: "[\d\-_]+"
          direct_flights:  0|1
          return_way:  0|1|2



bundles_default_api_calendar:
    pattern: /api/avia-calendar
    defaults: { _controller: BundlesDefaultBundle:Api:calendar}

bundles_default_api_complex_calendar:
    pattern:  /avia-calendar/{city}/{date}/{best_price}/{adults}/{return_way}/{children}/{infant}/{class}/{avia_company}/{direct_flights}
    defaults: { _controller: BundlesDefaultBundle:Search:calendar,adults: 1,class: Y ,children: 0,infant: 0,return_way : 2,direct_flights: 0, best_price: 1,avia_company: all}
    requirements:
          city: "[\w\-]+"
          date: "[\d\-_]+"
          direct_flights:  0|1
          return_way:  0|1
          best_price:  0|1

bundles_default.api.calendar_item_info:
    pattern: /api/avia-calendar/info
    defaults: { _controller: BundlesDefaultBundle:Api:calendarItemInfo}


bundles_default_api_create_pay:
    pattern: /pay-order/{orderID}
    defaults: { _controller: BundlesDefaultBundle:Pay:createPay}
    methods: POST
bundles_default_api_return_liqpay:
    pattern: /pay/liqpay/{orderID}
    defaults: { _controller: BundlesDefaultBundle:LiqPay:liqpaySuccess}
bundles_default.liqpay.get_status:
    pattern: /pay/liqpay/status/{orderID}
    defaults: {_controller: BundlesDefaultBundle:LiqPay:getStatus}
bundles_default_change_locale:
    pattern: /locale/{_locale}
    defaults: {_controller: BundlesDefaultBundle:Default:changeLocale}


