bundles_default_homepage:
    pattern:  /
    defaults: { _controller: BundlesDefaultBundle:Default:index }
bundles_default_search_city:
    pattern:  /api/city/search
    defaults: { _controller: BundlesDefaultBundle:Api:searchCity }
bundles_default_search:
    pattern:  /api/search
    defaults: { _controller: BundlesDefaultBundle:Api:search }

bundles_default_api_list:
    pattern:  /flights/{city_from_code}_{city_to_code}/{date_from}_{date_to}/{adults}_{children}/{class}/{currency}/{avia_company}/{direct_flights}{return_way}{best_price}
    defaults: { _controller: BundlesDefaultBundle:Api:list,date_to: 0 ,children: 0,return_way : 0,direct_flights: 0, best_price: 0}
    requirements:
          direct_flights:  0|1
          return_way:  0|1
          best_price:  0|1


