bundles_default_homepage:
    pattern:  /
    defaults: { _controller: BundlesDefaultBundle:Default:index }
bundles_default_search_city:
    pattern:  /api/city/search
    defaults: { _controller: BundlesDefaultBundle:Api:searchCity }
bundles_default_search:
    pattern:  /api/search
    defaults: { _controller: BundlesDefaultBundle:Api:search }


