bundles_default_homepage:
    pattern:  /
    defaults: { _controller: BundlesDefaultBundle:Default:index }
bundles_default_search_city:
    pattern:  /api/city/search
    defaults: { _controller: BundlesDefaultBundle:Api:searchCity }
bundles_default_search:
    pattern:  /api/search
    defaults: { _controller: BundlesDefaultBundle:Api:search }

bundles_default_api_list:
    pattern:  /flights/{city_from_code}/{city_to_code}/{date_from}/{adults}/{children}/{infant}/{class}/{currency}/{avia_company}/{direct_flights}{return_way}{best_price}/{date_to}
    defaults: { _controller: BundlesDefaultBundle:Api:list,date_to: null ,children: 0,infant: 0,return_way : 0,direct_flights: 0, best_price: 0}
    requirements:
          date_to: "[\d\-]*"
          date_from: "[\d\-]*"
          direct_flights:  0|1
          return_way:  0|1
          best_price:  0|1


