parameters:
#    bundles_default.example.class: Bundles\DefaultBundle\Example

services:
#    bundles_default.example:
#        class: %bundles_default.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
