imports:
    - { resource: forms.yml }
parameters:
#    bundles_default.example.class: Bundles\DefaultBundle\Example

services:
    bundle_default.controller_formatter:
        class: Bundles\DefaultBundle\Util\ControllerFormatter
        arguments: [@request_stack]

    budnels_default.locale_listener:
        class: Bundles\DefaultBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    bundels_default.payu.manager:
        class: Bundles\DefaultBundle\Model\Pay
        arguments:
            - merchant: "aviago.c"
              secretkey: "3+mm8|W(1?B58%g9P^4q"
              debug: 1
    bundles_default_util_route:
        class: Bundles\DefaultBundle\Util\RouteParams
        arguments: ["@admin.city.manager"]
    bundles_default.util.previous_flight:
        class:  Bundles\DefaultBundle\Model\Flights
        arguments:
          - @session
          - @router
          - @bundles_default_util_route
          - @translator
          - @admin.city.manager

    bundle_default.currency_manager:
        class: Bundles\DefaultBundle\Util\CurrencyManager
        arguments: [@session]

    bundles_default.search_form.options:
        class: Bundles\DefaultBundle\Form\SearchFormOptions
        arguments: [@translator]
#    bundles_default.liqupay_api:
#            class: Bundles\DefaultBundle\Model\LiqPayApi
#            arguments:
#              - "%liqupay.merchant_id%"
#              - "%liqupay.password%"
#              - @router




