imports:
    - { resource: forms.yml }
parameters:
#    bundles_default.example.class: Bundles\DefaultBundle\Example

services:
    budnels_default.locale_listener:
        class: Bundles\DefaultBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    bundels_default.payu.manager:
        class: Bundles\DefaultBundle\Model\Pay
        arguments:
            - merchant: "aviago.c"
              secretkey: "3+mm8|W(1?B58%g9P^4q"
              debug: 1
    bundles_default_util_route:
        class: Bundles\DefaultBundle\Util\RouteParams
        arguments: ["@admin.city.manager"]





