parameters:
#    bundles_default.example.class: Bundles\DefaultBundle\Example

services:
    budnels_default.locale_listener:
        class: Bundles\DefaultBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    budnels_default.form.type.order:
        class: Bundles\DefaultBundle\Form\OrderForm
        arguments: [@country.model.manager]
        tags:
            - { name: form.type, alias: order }
    budnels_default.form.type.search_form:
        class: Bundles\DefaultBundle\Form\SearchForm
        arguments: [@session,@translator]
        tags:
            - { name: form.type, alias: search_form }


