
api_list_flight:
    pattern:  /flights/{key}
    defaults: { _controller: BundlesDefaultBundle:Frontend:default}

bundles_default_api_book:
    pattern: /book/{key}
    defaults: { _controller: BundlesDefaultBundle:Frontend:default}

bundles_default_api_order:
    pattern: /order/{orderID}
    defaults: { _controller: BundlesDefaultBundle:Frontend:default}