Acme\AdminBundle\Entity\City:
    type: entity
    table: city
    repositoryClass: Acme\AdminBundle\Repository\CityRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        iata_code:
            type: string
        name_rus:
            type: string
        name_eng:
            type: string
        city_rus:
            type: string
        city_eng:
            type: string
        gmt_offset:
            type: string
        country_rus:
            type: string
        country_eng:
            type: string
        latitude:
            type: string
        longitude:
            type: string