Acme\AdminBundle\Entity\Gallery:
    type: entity
    table: gallery
    repositoryClass: Acme\AdminBundle\Repository\GalleryRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        description:
            type: text
            nullable: true
        is_show:
            type: boolean
            nullable: true
        position:
            type: integer
    oneToMany:
            media:
                targetEntity: Media
                mappedBy: gallery

