Acme\AdminBundle\Entity\Media:
    type: entity
    table: media
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            length: 10
            nullable: true
        name:
            type: string
            length: 255
        originName:
            type: string
            length: 255
            nullable: true
            column: origin_name
        mimeType:
            type: string
            length: 255
            column: mimeType
        size:
            type: string
            length: 255
        dimensions:
            type: string
            length: 255
        extension:
            type: string
            length: 10
        path:
            type: string
            length: 255
        avatar:
            type: boolean
            nullable: true
    manyToOne:
        slider:
            targetEntity: Slider
            inversedBy: media
        gallery:
            targetEntity: Gallery
            inversedBy: media

