Acme\AdminBundle\Entity\Order:
    type: entity
    table: orders
    repositoryClass: Acme\AdminBundle\Repository\OrderRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        state:
            type: string
            length: 1
        phone:
            type: string
            length: 255
            nullable: false
        price:
            type: float
        order_id:
            type: string
            length: 50
        email:
            type: string
            length: 255
            nullable: false
        date:
            type: datetime
            nullable: false
        passengers:
            type: json_array
            nullable: true
        info:
            type: json_array
            nullable: true
        pnr:
            type: string
            length: 255
            nullable: false
        order_info:
            type: json_array
            nullable: true



