parameters:
#    bundles_api.example.class: Bundles\ApiBundle\Example

services:
    avia.api.manager:
        class: Bundles\ApiBundle\Api\Api
        arguments: ["C330CA8C-DCDF-4CA8-A5E0-F5E4E1612440", @service_container]

    main.cache:
        class: Bundles\ApiBundle\Api\Model\Cache
        arguments:
          - @beryllium_cache

    avia.api.traslator:
        class: Bundles\ApiBundle\Api\Model\ResponseTranslator
        arguments: [@service_container]

    avia.api.search_entity_creator:
        class: Bundles\ApiBundle\Api\Util\TicketSearchEntityCreator
        arguments: [@avia.api.traslator]
    avia.api.ticket_entity_creator:
        class: Bundles\ApiBundle\Api\Util\TicketEntityCreator
        arguments: [@avia.api.traslator]
    avia.api.ticket_calendar_entity_creator:
        class: Bundles\ApiBundle\Api\Util\TicketCalendarEntityCreator
        arguments: [@avia.api.traslator]

